.TH roadfighter "6" "December 2017" "ROAD FIGHTER REMAKE" "Drive a car in a death race"

.SH NAME
roadfighter \- is a racing game at you drive car in a death race between you and a group of crazy drivers.
.br

.SH HOW TO PLAY
In Road Fighter you drive a car in a death race between you and a group of mad drivers.
Your aim? To reach the end of the checkpoint before you run out of fuel.
Sounds easy? Far from it, there's a lot of obstacles between your car and the checkpoints!
The game is divided in 6 stages and features 3 different difficulty levels:
.PP
.B GAME A
is for beginners. You will want to choose this when you play the game for the first time.
.PP
.B GAME B
is for advanced players. The game is quite hard to finish in this mode.
.PP
.B GAME C
is for crazy players. In this mode you will have serious problems to beat the game!
.PP
During the race, you should try not to hit the borders of the road.
Beware of the other cars, because they sometimes will try to push you to the border and make you crash.
Another important issue is the fuel. You should try to collect all the fuel recharges
that you can during the game. They are represented by the pink hearts.
.PP
You can also play the game with 2 players at the same time in split screen mode!
.PP
.SH CONTROLS
These are the default controls of the game. They can be redefined in the options menu.
.PP
.B KEY					ACTION
.br
Cursor up				Previous menu item
.br
Cursor down			Next menu item
.br
Cursor left			Steer left; previous menu
.br
Cursor right			Steer right; select menu item
.br
Space				Accelerate; select menu item
.br
F1					Pause
.br
ALT+ENTER				Switch between full-screen and window mode
.br
F12 or ESC			Quit
.br
.PP
.SH GAME OBJECTS
.br
.B Player car
.br
==========
.br
In the game you drive the red sports car.
If you are playing in 2 player mode, player 1 will drive
the red sports car and player 2 the yellow one.
.PP
.br
.B Fuel
.br
====
.br
During the race fuel charges will appear on the road in the form of pink hearts. Pick them up for more fuel and bonus points.
.PP
.br
.B Enemies
.br
=========
.br
During the race you will encounter other cars on the road.
There's different types of cars.
The drivers in the green cars are unlucky enough to be on the same road
where your crazy race is taking place. The blue cars are your opponents;
usually you are faster than them but don't get overconfident: sometimes they
can surprise you! Last of all are the drivers in the purple cars.
They are very suidical and will try to crash into you when you overtake them.
.PP
.br
.B Trucks
.br
=======
.br
You'd better avoid these big slow driving monsters!
.PP
.br
.B Obstacles
.br
==========
.br
Be careful of the water, oil and rock that sometimes appear on the road.
Water will slow down your car whereas oil will make your car spin.
And crashing into a rock at full speed is of course a very bad idea!
.PP
.SH AUTHOR
The ROAD FIGHTER REMAKE was written by Santi Ontanon.
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao], for the Debian project (but may be used by others).
